### ISSUE TITLE
Plot function in demospecstat6 & demospecstat9

### ISSUE THREAD

**Issue by katya-zossi** [Nikolaos-Matthaiakakis/MNPBEM#1]
I am having some trouble plotting the field enhancement in demospecstat6 & demospecstat9. I am getting the following error:

![error](https://user-images.githubusercontent.com/71917449/206933100-57cf71f3-a7b1-4379-8cae-8c0199df52b3.PNG)

I wrote some code in 2019 that worked a few years ago, but now I get the same error as above when using plot( p2, vecnorm( f.e ) ) for the field enhancement figure
[phd_field_enhancement.pdf](https://github.com/Nikolaos-Matthaiakakis/MNPBEM/files/10203470/phd_field_enhancement.pdf)

I tried to play around in MATLAB and fix the uipushtool error but I didn't have any luck. I would be very grateful for any help or advice on this. Thanks!

**Comment by Nikolaos-Matthaiakakis** [comment]
Hello, I might not be able to check this right away as I don't have access to my main computer. Since you mention that your code used to work in the past, which version of MNPBEM are you using? is it from this github page? I just downloaded the files and was unable to reproduce the error on matlab 2020b.

**Comment by katya-zossi** [comment]
Hi Nikolaos, thanks for the quick reply! I am using the MNPBEM from the github page and I was trying to run it in the online version of matlab/ mathworks. I have downloaded a local version of matlab on my laptop and now the code runs without the uipushtool error. 

However I did find a different bug whilst using matlab 2022b: 
To get the correct field enhancement plot, I have to change lines 40 & 67 of DEMOSPECSTAT6 from 
plot( eplate, vecnorm( fplate.e ) );
to:
plot( p, vecnorm( f.e, 2, 2 ) );

Otherwise the vecnorm function in matlab 2022b takes the norm of the field in the wrong direction (I don't think this was an issue in older versions of matlab, or at least in 2019). Coincidentally, this also fixes the uipushtool error in the online version of matlab/ mathworks. Here's a link to the vecnorm documentation in case it is helpful (I have to specify dim=2 otherwise it automatically chooses dim=1 which gives the wrong plot): https://uk.mathworks.com/help/matlab/ref/vecnorm.html

I expect the same bug will be in DEMOSPECSTAT9. Would it help if I update these files in the GitHub repo? 

Btw the download link for MNPBEM on the uni-graz website is currently broken: https://physik.uni-graz.at/de/mnpbem/

**Comment by Nikolaos-Matthaiakakis** [comment]
Hello, its great to hear that you resolved the issue. If you wish you can update the files with a comment about the old versions but I could also change it myself by tomorrow.

The development for the toolbox has actually ended. The link that you mention has been broken for a while but I am not responsible for this website, only the github page.
